version: '2'

services:
  memory:
    image: io.kabang.ext/memory:0.1.0
    container_name: memory
    oom_score_adj: -1000
    ports:
      - "8080:8080"
    networks:
      - memory
    restart: always

networks:
  memory:
    driver: bridge
    external: false
